begin;

create table if not exists public.pet_reminder_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  days_ahead integer not null default 7,
  in_app_enabled boolean not null default true,
  email_enabled boolean not null default false,
  whatsapp_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pet_reminder_preferences_days_ahead_check check (days_ahead between 1 and 90),
  constraint pet_reminder_preferences_user_unique unique (user_id)
);

create index if not exists idx_pet_reminder_preferences_user_id on public.pet_reminder_preferences(user_id);

drop trigger if exists trg_pet_reminder_preferences_set_updated_at on public.pet_reminder_preferences;
create trigger trg_pet_reminder_preferences_set_updated_at
before update on public.pet_reminder_preferences
for each row
execute function public.set_updated_at();

alter table public.pet_reminder_preferences enable row level security;

drop policy if exists pet_reminder_preferences_owner_manage on public.pet_reminder_preferences;
create policy pet_reminder_preferences_owner_manage
on public.pet_reminder_preferences
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create table if not exists public.pet_passport_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  action text not null,
  step_index integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint pet_passport_audit_events_step_index_check check (step_index is null or (step_index >= 0 and step_index <= 6))
);

create index if not exists idx_pet_passport_audit_events_user_created on public.pet_passport_audit_events(user_id, created_at desc);
create index if not exists idx_pet_passport_audit_events_pet_created on public.pet_passport_audit_events(pet_id, created_at desc);

alter table public.pet_passport_audit_events enable row level security;

drop policy if exists pet_passport_audit_events_select_own on public.pet_passport_audit_events;
create policy pet_passport_audit_events_select_own
on public.pet_passport_audit_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists pet_passport_audit_events_insert_own on public.pet_passport_audit_events;
create policy pet_passport_audit_events_insert_own
on public.pet_passport_audit_events
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.pets p
    where p.id = pet_passport_audit_events.pet_id
      and p.user_id = auth.uid()
  )
);

commit;
