begin;

create extension if not exists pgcrypto;

create table if not exists public.provider_admin_audit_events (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_provider_admin_audit_provider_created
  on public.provider_admin_audit_events(provider_id, created_at desc);
create index if not exists idx_provider_admin_audit_actor_created
  on public.provider_admin_audit_events(actor_id, created_at desc);

create table if not exists public.provider_review_response_history (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.provider_reviews(id) on delete cascade,
  provider_id bigint not null references public.providers(id) on delete cascade,
  previous_response text,
  new_response text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_provider_review_response_history_review_created
  on public.provider_review_response_history(review_id, created_at desc);
create index if not exists idx_provider_review_response_history_provider_created
  on public.provider_review_response_history(provider_id, created_at desc);

alter table public.provider_admin_audit_events enable row level security;
alter table public.provider_review_response_history enable row level security;

drop policy if exists provider_admin_audit_select_admin_v1 on public.provider_admin_audit_events;
create policy provider_admin_audit_select_admin_v1
on public.provider_admin_audit_events
for select
to authenticated
using (public.is_admin());

drop policy if exists provider_admin_audit_insert_admin_v1 on public.provider_admin_audit_events;
create policy provider_admin_audit_insert_admin_v1
on public.provider_admin_audit_events
for insert
to authenticated
with check (public.is_admin());

drop policy if exists provider_review_response_history_select_v1 on public.provider_review_response_history;
create policy provider_review_response_history_select_v1
on public.provider_review_response_history
for select
to authenticated
using (public.is_admin() or public.is_provider_owner(provider_id));

drop policy if exists provider_review_response_history_insert_v1 on public.provider_review_response_history;
create policy provider_review_response_history_insert_v1
on public.provider_review_response_history
for insert
to authenticated
with check (public.is_admin() or public.is_provider_owner(provider_id));

commit;
